"""Add title, original_filename, key to Result

Revision ID: 103237c534b7
Revises: ed828a0a4657
Create Date: 2025-06-02 16:41:47.124290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103237c534b7'
down_revision = 'ed828a0a4657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('key', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('key')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
